services:
  - type: web
    name: youtube-transcript-api
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PORT
        value: 10000
